apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  namespace: 
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - netflix
  template: 
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: c1
        image: devopsinsiders/netflix-clone
        ports:
        - containerPort: 80
